export const DEFAULTS = {
  model: 'anthropic/claude-sonnet-4-20250514',
  temperature: 0.7,
  maxTokens: 4096,
  thinkingLevel: 'medium',
  compactionThreshold: 200,
  compactionBytesThreshold: 300_000,
  compactionKeepRecent: 50,
  rateLimitPerMinute: 20,
  pairingCodeTtlSeconds: 300,
  systemPrompt: 'You are a helpful AI assistant.',
  memoryRetrievalTopK: 10,
  memoryDeduplicationThreshold: 0.9,
  memoryAutoExtractEnabled: true,
  memoryEmbeddingModel: '@cf/baai/bge-small-en-v1.5' as const,
  fetchMaxResponseBytes: 100_000,
  fetchTimeoutMs: 30_000,
  mcpConnectTimeoutMs: 15_000,
  mcpToolExecTimeoutMs: 30_000,
} as const;
